[package]
name = "haematite_ser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
haematite_models = { path = "../haematite_models" }

serde = "1.0.147"
serde_json = "1.0.87"
