[package]
name = "haematite_events"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amqprs = "1.5.2"
async-trait = "0.1.77"
lapin = "2.3.1"
serde = "1.0.195"
serde_json = "1.0.112"
